version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - harshit
    volumes:
      - servervol:/app/serverdata

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - clientvol:/app/clientdata
    networks:
      - harshit

volumes:
  servervol:
  clientvol:

networks:
  harshit:
